## Profiler des données 
1 - Chargez les librairies nécessaires  
2 - Chargez les fichiers  
3 - Récupérez toutes les informations pour chaque colonnes

#### 1 - Chargement des libriairies pour les traitement de DB csv

In [2]:
import pandas as pd

#### 2 - Chargement des fichiers xls pour traitement

In [6]:
# Charge le fichier au format voulu
df_profile = pd.read_csv("../data/2016_Building_Energy_Benchmarking.csv")

# Voir les noms des feuilles disponibles si il y en a 
print(list(df_profile.keys()))

['OSEBuildingID', 'DataYear', 'BuildingType', 'PrimaryPropertyType', 'PropertyName', 'Address', 'City', 'State', 'ZipCode', 'TaxParcelIdentificationNumber', 'CouncilDistrictCode', 'Neighborhood', 'Latitude', 'Longitude', 'YearBuilt', 'NumberofBuildings', 'NumberofFloors', 'PropertyGFATotal', 'PropertyGFAParking', 'PropertyGFABuilding(s)', 'ListOfAllPropertyUseTypes', 'LargestPropertyUseType', 'LargestPropertyUseTypeGFA', 'SecondLargestPropertyUseType', 'SecondLargestPropertyUseTypeGFA', 'ThirdLargestPropertyUseType', 'ThirdLargestPropertyUseTypeGFA', 'YearsENERGYSTARCertified', 'ENERGYSTARScore', 'SiteEUI(kBtu/sf)', 'SiteEUIWN(kBtu/sf)', 'SourceEUI(kBtu/sf)', 'SourceEUIWN(kBtu/sf)', 'SiteEnergyUse(kBtu)', 'SiteEnergyUseWN(kBtu)', 'SteamUse(kBtu)', 'Electricity(kWh)', 'Electricity(kBtu)', 'NaturalGas(therms)', 'NaturalGas(kBtu)', 'DefaultData', 'Comments', 'ComplianceStatus', 'Outlier', 'TotalGHGEmissions', 'GHGEmissionsIntensity']

#### 3 - Extraire toutes les infos pour chaque colonnes

In [ ]:
def renseigne(df,name):
    df_inv = pd.DataFrame({
        'colonne': df.columns,
        'type': df.dtypes.values,
        'longueur_max': df.apply(lambda col: col.astype(str).str.len().max()).values,
        'non_null': df.notnull().sum().values,
        'nan': df.isnull().sum().values, 
        'valeur_unique':df.nunique().values,
    })
    return df_types

# Boucle sur chaque feuille si necessaire
file = {"seattle_bench": df_profile}

for nom_feuille, df in file.items():
    display(f"\n--- Feuille : {nom_feuille} ---")
    display(renseigne(df,"seattle_bench"))

'\n--- Feuille : seattle_bench ---'

,colonne,type,longueur_max,non_null,nan,valeur_unique
0,OSEBuildingID,int64,5.0,3376,0,3376
1,DataYear,int64,4.0,3376,0,1
2,BuildingType,str,20.0,3376,0,8
3,PrimaryPropertyType,str,27.0,3376,0,24
4,PropertyName,str,72.0,3376,0,3362
5,Address,str,41.0,3376,0,3354
6,City,str,7.0,3376,0,1
7,State,str,2.0,3376,0,1
8,ZipCode,float64,7.0,3360,16,55
9,TaxParcelIdentificationNumber,str,25.0,3376,0,3268
10,CouncilDistrictCode,int64,1.0,3376,0,7
11,Neighborhood,str,22.0,3376,0,19
12,Latitude,float64,11.0,3376,0,2876
13,Longitude,float64,12.0,3376,0,2656
14,YearBuilt,int64,4.0,3376,0,113
15,NumberofBuildings,float64,5.0,3368,8,17
16,NumberofFloors,int64,2.0,3376,0,50
17,PropertyGFATotal,int64,7.0,3376,0,3195
18,PropertyGFAParking,int64,6.0,3376,0,496
19,PropertyGFABuilding(s),int64,7.0,3376,0,3193
20,ListOfAllPropertyUseTypes,str,255.0,3367,9,466
21,LargestPropertyUseType,str,52.0,3356,20,56
22,LargestPropertyUseTypeGFA,float64,9.0,3356,20,3122
23,SecondLargestPropertyUseType,str,52.0,1679,1697,50
24,SecondLargestPropertyUseTypeGFA,float64,11.0,1679,1697,1352
25,ThirdLargestPropertyUseType,str,52.0,596,2780,44
26,ThirdLargestPropertyUseTypeGFA,float64,11.0,596,2780,501
27,YearsENERGYSTARCertified,object,60.0,119,3257,65
28,ENERGYSTARScore,float64,5.0,2533,843,100
29,SiteEUI(kBtu/sf),float64,11.0,3369,7,1085
30,SiteEUIWN(kBtu/sf),float64,11.0,3370,6,1105
31,SourceEUI(kBtu/sf),float64,11.0,3367,9,1648
32,SourceEUIWN(kBtu/sf),float64,12.0,3367,9,1694
33,SiteEnergyUse(kBtu),float64,11.0,3371,5,3354
34,SiteEnergyUseWN(kBtu),float64,11.0,3370,6,3341
35,SteamUse(kBtu),float64,11.0,3367,9,131
36,Electricity(kWh),float64,12.0,3367,9,3352
37,Electricity(kBtu),float64,11.0,3367,9,3351
38,NaturalGas(therms),float64,11.0,3367,9,2109
39,NaturalGas(kBtu),float64,11.0,3367,9,2109
40,DefaultData,bool,5.0,3376,0,2
41,Comments,float64,NaN,0,3376,0
42,ComplianceStatus,str,28.0,3376,0,4
43,Outlier,str,12.0,32,3344,2
44,TotalGHGEmissions,float64,8.0,3367,9,2818
45,GHGEmissionsIntensity,float64,5.0,3367,9,511

In [9]:
display(df_profile.head(3))

,OSEBuildingID,DataYear,BuildingType,PrimaryPropertyType,PropertyName,Address,City,State,ZipCode,TaxParcelIdentificationNumber,...,Electricity(kWh),Electricity(kBtu),NaturalGas(therms),NaturalGas(kBtu),DefaultData,Comments,ComplianceStatus,Outlier,TotalGHGEmissions,GHGEmissionsIntensity
0,1,2016,NonResidential,Hotel,Mayflower park hotel,405 Olive way,Seattle,WA,98101.0,0659000030,...,1.156514e+06,3946027.0,12764.52930,1276453.0,False,NaN,Compliant,NaN,249.98,2.83
1,2,2016,NonResidential,Hotel,Paramount Hotel,724 Pine street,Seattle,WA,98101.0,0659000220,...,9.504252e+05,3242851.0,51450.81641,5145082.0,False,NaN,Compliant,NaN,295.86,2.86
2,3,2016,NonResidential,Hotel,5673-The Westin Seattle,1900 5th Avenue,Seattle,WA,98101.0,0659000475,...,1.451544e+07,49526664.0,14938.00000,1493800.0,False,NaN,Compliant,NaN,2089.28,2.19